### ISSUE TITLE
server_var() int conversion

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#10]
`es_xset test_var 10_10_10`
`es_msg server_var(test_var)`

This will message 101010 instead of 10_10_10.
If there are only _ and int numbers it will remove the _

if there is any other string included it will keep the original structure

Edit: It seems that _ is actually part of the integer class,

**Comment by Ayuto** [comment]
Yeah, I think this notation has been added with Python 3.6. I will take a look at it later.
