### ISSUE TITLE
playerset color

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#11]
Due to es_mathparse not beeing available using playerset color will result in the playermodel to completely vanish. Killing the player while vanished will crash the client (not the server).

**Comment by Ayuto** [comment]
I will add es_mathparse very soon.

I already created a Python binding for MuParser. That's the library EventScripts also used to implement es_mathparse:
https://github.com/Ayuto/Py-MuParser
