### ISSUE TITLE
playerset viewcoord

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#12]
I was testing playerget and playerset viewcoord with this code:

```
event player_say
{
	if (event_var(text) = "test") do
	{
		es playerget viewcoord event_var(userid) wcs_x1 wcs_y1 wcs_z1
			}
	if (event_var(text) = "test2") do
	{
		es playerset viewcoord event_var(userid) server_var(wcs_x1) server_var(wcs_y1) server_var(wcs_z1)
	}	
}
```

playerget viewcoord returns the same results as Player.view_coordinates.

But playerset viewcoord does not set it to the location it should.

![getting the location](https://user-images.githubusercontent.com/33634496/35182574-fee374bc-fdd7-11e7-93d0-6dce0b16a582.png)

![setting the location](https://user-images.githubusercontent.com/33634496/35182578-062da918-fdd8-11e7-8efa-e9bbda159532.png)

**Comment by Ayuto** [comment]
It also does not seem to work properly in the original ES when testing with CS:S.

**Comment by Ayuto** [comment]
I decided to not fix it, because it's a bug in ES, not the emulator.
