### ISSUE TITLE
Source Python Errors

### ISSUE THREAD

**Issue by Raklatif** [Ayuto/EventScripts-Emulator#16]
Initializing EventScripts...

[SP] Encountered a Warning:
  File '..\addons\source-python\plugins\es_emulator\eventscripts\esc\cmds\__init__.py', line 77: DeprecationWarning
    inspect.getargspec() is deprecated, use inspect.signature() or
        inspect.getfullargspec()

Command alias already exists.
[EventScripts] Loaded esc
ES Emulator has been loaded successfully!
[SP] Successfully loaded plugin 'es_emulator'.
Network: IP 192.168.1.111, mode MP, dedicated Yes, ports 27015 SV / 27005 CL

[SP] Encountered a Warning:
  File '..\addons\source-python\plugins\es_emulator\eventscripts\esc\parse.py', line 62: DeprecationWarning
    generator 'getcommands' raised StopIteration

[corelib/interfaces/register 232] es_foreachval: Unable to retrieve a pointer of this object.
[SP] Loading plugin 'wcs'...

[SP] Encountered a Warning:
  File '..\addons\source-python\packages\site-packages\path.py', line 1713: DeprecationWarning
    path is deprecated. Use Path instead.

[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[console] es: Syntax: es <commandstring>
[SP] Successfully loaded plugin 'wcs'.

**Comment by Ayuto** [comment]
Those are warnings, not errors. 

- The first warning is already fixed.
- The path warning should also be fixed as I just updated the last two occurences.
- Command ``alias`` now only gets registered if it doesn't already exist.
- The ``Syntax: es`` warnings are probably caused by wcs and not by the emulator.

So, the last warning left is the ``getcommands`` warning.

**Comment by Ayuto** [comment]
This commit https://github.com/Ayuto/EventScripts-Emulator/commit/71a5987f6300b7ce9876163d481d892e3f39d267 fixes the last warning.
