### ISSUE TITLE
Cyrilic 

### ISSUE THREAD

**Issue by lphsqr** [Ayuto/EventScripts-Emulator#19]
Hey. es_emulator es_tell produces hieroglyphics instead of Russian, tried utf8 with bom, no bom
example:
es_tell userid #multi "#lightgreen damage server_var (wcs_dmg)"
on server:
hieroglyphs server_var (wcs_dmg)

**Comment by Ayuto** [comment]
Yes, it's a bug that has been reported already. https://github.com/Ayuto/EventScripts-Emulator/issues/15
