### ISSUE TITLE
event_vars switching mid block

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#20]
Hey,

I noticed behavior that was different to the original EventScripts.
When I deal damage in a player_hurt event to the damaging player the event_vars will mid event
This example shows what I mean

```
event player_hurt
{

	if (event_var(weapon) != point_hurt) do

	{

		es_msg event_var(attacker)
		es wcs_dealdamage event_var(attacker) event_var(userid) 5
		es_msg event_var(attacker)

	} 

}
```

When shooting a bot event_var(attacker) will first contain my userid then after doing damage to me by the bot with a point hurt (that is what wcs_dealdamage does) event_var(attacker) will return the bot's userid.

I kinda understand where that problem might be coming from, but the event_vars should not change mid event I think.

**Comment by Ayuto** [comment]
Actually, I'm unable to reproduce the issue. Tested it with the following snippet on CS:GO and CS:S:
```
event player_hurt
{
	if (event_var(weapon) != point_hurt) do
	{
		es_msg before event_var(attacker)
		es damage event_var(userid) 50 32 event_var(userid)
		es_msg after event_var(attacker)
	}
}
```
