### ISSUE TITLE
Playerset model [Client side game crash]

### ISSUE THREAD

**Issue by ManifestManah** [Ayuto/EventScripts-Emulator#25]
When using the playerset model command to change a player's model to something that aren't designed for players to play as, such as a stack of cinderblocks, a barrel, or the likes then when the player dies his game will crash. This is not a server crash, but purely a client side crash, this will with 100% certainty happen to the player who has the model set, but will also happen to everyone else who is looking at or in the direction of the player with the model.

Aside from when the player dies, everything else works just perfect even despit the models used might be missing multiple animation sequences it still causes zero crashes, at least from our testing so far. 

I've asked around, and found out that this can be fixed by merely changing the player's model back to it's original one (or any of the default player models) just prior to the player's death occuring.

![Model Issue (Supposed to be error)](https://user-images.githubusercontent.com/15453480/58248792-67e4f700-7d5d-11e9-8f85-3dc0edd3319d.png)
![Model Issue Crow](https://user-images.githubusercontent.com/15453480/58248798-6b787e00-7d5d-11e9-95a4-4b63a49f88a8.png)
![Model Issues](https://user-images.githubusercontent.com/15453480/58248806-6e736e80-7d5d-11e9-98a9-f19247fafc56.png)

**Comment by Ayuto** [comment]
I think that's rather a bug in the game - not in the emulator.
