### ISSUE TITLE
[EventScripts Emulator] Not Loading On Windows.

### ISSUE THREAD

**Issue by ManifestManah** [Ayuto/EventScripts-Emulator#39]
I have been assisting a friend of mine in trying to set up a new Warcraft-Source server.
We have successfully installed MetaMod, the newest version of Source-Python, and when we added the most recent version of the Emulator (Downloaded: 13.07-2020) it wasn't able to load. 

My friend's server is running the Windows operating system and although he experienced issues I have not experienced the same running it on any of my Linux servers in the past, so it leads me to believe it is a pure Windows related problem.

**Below are the errors we received from the server console when attempting to install the Emulator on the Windows server.**
```
[SP] Loading plugin 'es_emulator'...
 
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\plugins\command.py", line 164, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "..\addons\source-python\packages\source-python\plugins\manager.py", line 194, in load
    plugin._load()
  File "..\addons\source-python\packages\source-python\plugins\instance.py", line 74, in _load
    self.module = import_module(self.import_name)
  File "..\addons\source-python\plugins\es_emulator\es_emulator.py", line 6, in <module>
    import muparser
 
ImportError: DLL load failed: The specified module could not be found.
 
 
[SP] Plugin 'es_emulator' was unable to be loaded.
```

**This is the version of Source-Python we are using on the Windows server:**

```
IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : c677ef51b35a70ce8d7a95bf476c21c1
Date          : 2020-07-14 12:38:43.416087
OS            : Windows-10-10.0.17763
Game          : csgo
SP version    : 698
Github commit : 2c9c421a280e5f7dce861af9bf1f31d8c08ab2c7
Server plugins:
   00: Metamod:Source 1.10.7-dev
   01: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
   00: wcs, 2020.07.03-1, https://forums.sourcepython.com/viewtopic.php?f=7&t=1925
--------------------------------------------------------
```

**Comment by Ayuto** [comment]
Try installing the 32 bit version of ``Visual C++ Redistributable for Visual Studio 2015``.
https://www.microsoft.com/en-US/download/details.aspx?id=48145
