### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#4]
https://github.com/Ayuto/EventScripts-Emulator/blob/4680652a2c8c69d62e266ebce2ce02349b039875/addons/source-python/plugins/es_emulator/helpers.py#L241

The color codes are a not quite right.

3 = Purple
4 = Green
5 = Lightgreen
6 = Darkgreen

**Comment by Ayuto** [comment]
These are the color codes that ES was also using and it's working fine in CS:S. Are you perhaps testing CS:GO?

**Comment by kamikazekuh** [comment]
Oh yes its CS:GO, sorry, I forgot to mention that.
Maybe a check for the game would be a possibility
