### ISSUE TITLE
Hit Group - Knife attacks returning 0

### ISSUE THREAD

**Issue by ManifestManah** [Ayuto/EventScripts-Emulator#40]
As I was working on a new character of my own, I believe I might've stumbled upon a bug.
The script that I am working on is supposed to deal additional damage to the victim if a certain hitgroup is hit, the character in this case can only wield knives. 

As I was creating the skill I noticed that the event_var(hitgroup) always return the value 0, if the weapon used to inflict the damage is a knife. Below is a code to replicate this.

```
event player_hurt
{
	es_msg This is hitgroup: event_var(hitgroup)
}
```

I am using the newest version of the Emulator. 
Are there any chance of a fix for this? This working would have a huge impact on what I am trying to create :-)

**Comment by Ayuto** [comment]
What's the output of ``sp info``?

**Comment by ManifestManah** [comment]
The sp info output at the time would be this:

```
--------------------------------------------------------
Checksum      : 3a539eb78239fc93f8f6f382d3c397df
Date          : 2020-08-01 12:18:11.622719
OS            : Linux-4.15.0-88-generic-x86_64-with-debian-stretch-sid
Game          : csgo
SP version    : 699
Github commit : 7e06ce8e445e17425dfcecdad5895473c294fabc
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
   01: Metamod:Source 1.10.7-dev
SP plugins:
   00: es_emulator, https://github.com/Ayuto/EventScripts-Emulator
   01: es_emulator_events
   02: wcs, 2020.07.31-4, https://forums.sourcepython.com/viewtopic.php?f=7&t=1925
   03: commandsx
--------------------------------------------------------
```

**Comment by Ayuto** [comment]
Just checked it on CS:GO and was able to confirm my assumption. The hitgroup isn't set in CS:GO when using a knife. I also tested reading two attributes (hitgroup and last_hitgroup) from SP's ``Player`` class and they also returned 0. So, I'm pretty sure that it's a restriction of the engine. With a little bit effort it might be possible to figure out the hitgroup on our own, but that not job of this emulator.
