### ISSUE TITLE
[es_tell   wcs_centertell]Characters cannot be displayed after translation

### ISSUE THREAD

**Issue by ghost** [Ayuto/EventScripts-Emulator#42]
es_tell  

I can't display the characters after I translate in Chinese. I can only display the rest of English

**Comment by Ayuto** [comment]
Could you please upload your test script?

**Comment by Ayuto** [comment]
@nancheng0 I'm unable to reproduce the issue using the following code:
```
event player_jump
{
    es_centertell event_var(userid) 震撼了你！
}
```
Thus, I guess it's a problem with wcs_centertell. You should create an issue here:
https://github.com/ThaPwned/WCS

**Comment by nancheng0** [comment]
thank you, i will try&nbsp;



---Original---
