### ISSUE TITLE
[es_tell wcs_centertell]Characters cannot be displayed after translation

### ISSUE THREAD

**Issue by nancheng0** [Ayuto/EventScripts-Emulator#43]
https://github.com/ManifestManah/Racepack-Standard/blob/master/addons/source-python/plugins/es_emulator/eventscripts/wcs/tools/standard/archmage_proudmoore/es_archmage_proudmoore.txt#L50

es wcs_centertell event_var(userid) event_var(es_attackername) struck you with his earthquake!

change it to

es wcs_centertell event_var(userid) event_var(es_attackername) 震撼了你！

it seems that wcs_centertell / es_centertell /es_tell l Unable to use Chinese Translation

**Comment by Ayuto** [comment]
Duplicate #42
