### ISSUE TITLE
csgo's weaponlib needs updating

### ISSUE THREAD

**Issue by NosferatuJoe** [Ayuto/EventScripts-Emulator#47]
MP5SD is missing from csgo's weaponlib, not sure if there are any other new weapons that they've added.
If I knew how to retrieve all the info, I'd gladly create a PR for you :)

**Comment by Ayuto** [comment]
Thanks for the reminder! It's simply a copy of SP's file:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/data/source-python/weapons/csgo.ini
