### ISSUE TITLE
es_userdead / es_attackerdead

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#5]
https://github.com/Ayuto/EventScripts-Emulator/blob/c2737c75b932f9ff051ed472a6f16ba876e19049/addons/source-python/plugins/es_emulator/logic.py#L142

es_userdead and es_attackerdead should return either 0 or 1 as an int value but since player.dead returns a bool es_userdead returns False or True, not 0 or 1.

**Comment by Ayuto** [comment]
Thanks!
