### ISSUE TITLE
Segmentation fault crash (+ crashdump)

### ISSUE THREAD

**Issue by NosferatuJoe** [Ayuto/EventScripts-Emulator#53]
I've noticed that whenever I run ONLY wcs & emulator, in this order; 
sp plugin load es_emulator
sp plugin load wcs

that the server tends to crash 1-2 times a day with a segmentation fault error. I also let wcs run solely to see if it would crash but that did not happen, hence I'm pretty sure that it's an issue in the emulator.

At the moment I'm using the sourcemod's accelerator to obtain a crash dump file for the crashes that happen, so for now it's a waiting game. Whenever I retrieve the crash dump I'll include it into this issue.

After next crash I'll run emulator alone and see if it also crashes after a certain amount of time, that way I can be sure that it's 100% an issue with the emulator.

PS: YES I already disabled sourcemod/metamod to see if this caused the crash, which didn't, so I isolated it to the emulator.

**Comment by NosferatuJoe** [comment]
A link to the crashdump/accelerator page:
https://crash.limetech.org/oukjjiyhrmps

Yes I'm aware that there are some extra sourcemod plugins running besides the base, I forgot to turn them off. I will provide a new crash dump without them loaded probably tomorrow.

Hope this might be useful.

**Comment by Ayuto** [comment]
There are two types of errors:
1. Simple Python errors aka exceptions. Those are always caught and written to the log or printed to the console. Those usually don't cause crashes. They simply cause a malfunction (e. g. a player will not get a special ability or a menu is not showing or doesn't do what it is supposed to do).
2. Segmentation faults. Those are critical and are caught by the Accelerator. As far as I know it's very similar to starting your server with the ``-debug`` option. This option will generate a ``debug.log`` file in your server's game directory if your server crashes.

Regarding the compatibility note:
It should actually just apply to Windows servers, because we have added special segmentation fault handlers at certain places that catch the segmentation fault and throw a Python exception instead. So, instead of crashing you will have a simple Python exception. But as I said that is only implemented on Windows (we should update the compatibilty note).

**Comment by NosferatuJoe** [comment]
@Ayuto 

Thanks a ton for clarifying this, now I fully understand the difference. Before, I thought that exceptions could also crash the server but that's apparently not the case hehe..

To get back to the point; 
I'm running my csgo server on linux, but not sure which distro, if required I could ask my host.
I also noticed that you can only see limited info on the link I provided. Can you recommend a good upload host so I can upload the minidump for you, or is there a way I can give you full access to my accelerator logs?

**Comment by Ayuto** [comment]
Well, you can start your server with the debug option and post the log file here. Or grab the full log from the Accelerator and post it here.

**Comment by NosferatuJoe** [comment]
I added the accelerator minidump as a .zip since github doesn't support the .dmp fileformat.
I'd also like to add the coredumps but they're 2GB, so not sure where I should upload those.
[crash_oukjjiyhrmps (1).zip](https://github.com/Ayuto/EventScripts-Emulator/files/5887951/crash_oukjjiyhrmps.1.zip)

**Comment by NosferatuJoe** [comment]
I acquired another crashdump which is 60MB, still too big for github so I uploaded it to zippyshare.

https://www65.zippyshare.com/v/SLFlQn3f/file.html

**Comment by Ayuto** [comment]
I actually just need the ``debug.log`` file, which can be posted as texte here. Additionally, the output of ``sp info`` will be helpful.

**Comment by NosferatuJoe** [comment]
I would gladly provide you with the debug.log file but I can't seem to find it anywhere, where should this be located?
Also, is it obtained with the -debug parameter?

Sorry for my incompetence, it's my first time working with debug logs and providing debug info on github. So this is kind of a learning curve for me, but I'd gladly provide you with everything that's necessary. Just keep in mind that I'm hiring a linux server from a gameserver provider host and have to ask them to active certain things for debugging purposes.

**Comment by Ayuto** [comment]
Yes, you just add ``-debug`` to your start arguments for your server, disable everything except SP, the emulator and wcs and then wait for a crash. If a crash occurs, it will generate a ``debug.log`` in ``/home/dathost/csgo_ds/``.

**Comment by NosferatuJoe** [comment]
My provider added the -debug flag, but now I'm unable to connect to the server. Is this intended? If so, then I should just monitor the console and wait for a crash, then ask the provider for the debug.log right?

**Comment by Ayuto** [comment]
No, this is not intended. It should actually work as usual.

**Comment by NosferatuJoe** [comment]
I think it might've been a problem with the host. Anyways whilst awaiting my request for the debug.log I can already provide you with a snippet from the console.log which might be helpful (not sure).

```
Feb  4 07:36:52:  L 02/04/2021 - 07:36:52: Starting Freeze period
Feb  4 07:36:52:  Bad SetLocalOrigin(-153.523193,130.657639,21564.195312) on weaponworldmodel
Feb  4 07:36:52:  IVP Failed at ../ivp_utility/ivu_vhash.cxx 157
Feb  4 07:36:52:  IVP Failed at ../ivp_utility/ivu_vhash.cxx 157
Feb  4 07:36:52:  
Feb  4 07:36:52:  IVP Failed at ../ivp_utility/ivu_vhash.cxx 157
Feb  4 07:36:52:  
Feb  4 07:36:53:  /home/dathost/csgo_ds/srcds_run: line 318:    18 Segmentation fault      (core dumped) $HL_CMD
Feb  4 07:36:53:  cat: hlds.11.pid: No such file or directory
Feb  4 07:36:53:  email debug.log to linux@valvesoftware.com
Feb  4 07:36:53:  Thu Feb  4 07:36:53 UTC 2021: Server Quit
Feb  4 07:36:53:  --- SERVER EXITED ---
```

**Comment by NosferatuJoe** [comment]
This is the full debug.log:
```
----------------------------------------------
CRASH: Wed Feb  3 10:30:32 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey E6C3089F10F78270B5E71D6803031DBD +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 10:33:09 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey E6C3089F10F78270B5E71D6803031DBD +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 10:36:00 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey E6C3089F10F78270B5E71D6803031DBD +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 10:40:33 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey E6C3089F10F78270B5E71D6803031DBD +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 10:42:15 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey 28F8CD94F0D0FC81336676D5E243FD7A +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 11:11:03 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey 28F8CD94F0D0FC81336676D5E243FD7A +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 12:19:27 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey 28F8CD94F0D0FC81336676D5E243FD7A +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 12:21:34 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey 28F8CD94F0D0FC81336676D5E243FD7A +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 12:21:52 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey 28F8CD94F0D0FC81336676D5E243FD7A +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Wed Feb  3 12:24:46 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey 27B8A591ABDA4FF2BD6BD804109B4A28 +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Thu Feb  4 02:51:57 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey 27B8A591ABDA4FF2BD6BD804109B4A28 +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
----------------------------------------------
----------------------------------------------
CRASH: Thu Feb  4 07:36:53 UTC 2021
Start Line: ./srcds_linux -game csgo -norestart -nowatchdog -usercon -secure -nobreakpad -authkey 27B8A591ABDA4FF2BD6BD804109B4A28 +exec dathost_auto_generated.cfg +game_type 0 +game_mode 0 -tickrate 64.0 +hostport 27697 +net_public_adr sansa.dathost.net -maxplayers_override 10 +sv_pure 0 -nohltv +host_workshop_collection 2187398257 +workshop_start_map 125620805 -debug +map de_dust
End of Source crash report
```

To me this seems rather useless but maybe it's of use to you..

**Comment by NosferatuJoe** [comment]
Another crash without wcs being loaded. So the only plugin loaded is es_emulator. Also it appears to always happen at a round start.

```
Feb  8 21:22:52:  L 02/08/2021 - 21:22:52: World triggered "Round_Start"
Feb  8 21:22:57:  /home/dathost/csgo_ds/srcds_run: line 318:    19 Segmentation fault      (core dumped) $HL_CMD
Feb  8 21:22:57:  cat: hlds.12.pid: No such file or directory
Feb  8 21:22:57:  email debug.log to linux@valvesoftware.com
Feb  8 21:22:57:  Mon Feb  8 21:22:57 UTC 2021: Server Quit
Feb  8 21:22:57:  --- SERVER EXITED ---
```

Will add debug.log later

**Comment by Ayuto** [comment]
Ah, that is giving us a hint! Could you please try to run the emulator with ``eventscripts_autorefreshvars`` being set to ``0``. If that crashes as well, could you please set ``eventscripts_debug`` to ``5`` and test again?

**Comment by NosferatuJoe** [comment]
I tried with eventscripts_autorefreshvars "0" but it also crashed, same behaviour. So now I'm trying with eventscripts_autorefreshvars "1" & eventscripts_debug 5. Hope it'll show us some insight whenever the server crashes.

**Comment by NosferatuJoe** [comment]
For some reason the server ain't crashing after I set eventscripts_debug to "5". I guess this is pure coincidence?

**Comment by NosferatuJoe** [comment]
Where can I find the logs for eventscripts_debug 5?

**Comment by Ayuto** [comment]
It should be written to your console. So, if you log your console with ``-condebug``, you should find a ``console.log`` somewhere in your game server directory.

**Comment by NosferatuJoe** [comment]
I found it but unfortunately there is not much info, the last lines are these:

```
Feb 13 13:06:51:  Checking all scripts...
Feb 13 13:06:51:  Script pack registration scanning...
Feb 13 13:06:51:  Checking all scripts...
Feb 13 13:06:51:  Script pack registration scanning...
Feb 13 13:06:51:  Checking all scripts...
Feb 13 13:06:51:  Script pack registration scanning...
Feb 13 13:06:51:  Checking all scripts...
Feb 13 13:06:51:  Script pack registration scanning...
Feb 13 13:06:51:  Checking all scripts...
Feb 13 13:06:51:  L 02/13/2021 - 13:06:51: "omq what is that<231><BOT><TERRORIST>" [318 -802 368] killed "jks<228><BOT><CT>" [436 -702 272] with "ak47"
Feb 13 13:06:51:  Script pack registration scanning...
Feb 13 13:06:51:  Checking all scripts...
Feb 13 13:06:51:  Script pack registration scanning...
Feb 13 13:06:51:  Checking all scripts...
Feb 13 13:06:51:  Script pack registration scanning...
Feb 13 13:06:51:  Checking all scripts...
```
I did notice again that it's aproximately 50-60s after a round_start when it crashes, and it always takes like 4-6 hours of uptime before it happens. To me it seems like some kind of memory leak which causes the server to crash eventually.

**Comment by NosferatuJoe** [comment]
The only thing I can find in the logs is this: 

```
2021-02-16 11:48:53 - sp	-	MESSAGE	[SP] Loading plugin 'es_emulator'...
2021-02-16 11:48:53 - sp	-	MESSAGE	[SP] Successfully loaded plugin 'es_emulator'.
2021-02-16 11:52:08 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/plugins/manager.py", line 231, in unload
    plugin._unload()
  File "../addons/source-python/packages/source-python/plugins/instance.py", line 81, in _unload
    self.module.unload()
  File "../addons/source-python/plugins/es_emulator/es_emulator.py", line 60, in unload
    'Unloading EventScripts Emulator is not implemented yet. The emulator '

NotImplementedError: Unloading EventScripts Emulator is not implemented yet. The emulator is now in an unsuitable state. You need to restart your server.
```

Which is weird since nowhere have I set an unload/reload command.. So not sure why it's throwing this error if I'm just loading the plugin in autoexec.

**Comment by NosferatuJoe** [comment]
Server still crashes with latest stable SP version.
Tested SP with NO plugins loaded and it didn't crash, so I'm 100% sure that it's the emulator. Problem is that there are no error logs or indications what part of the emulator is causing the crashes to happen.

```
Feb 19 15:37:24:  sp info
Feb 19 15:37:24:  
Feb 19 15:37:24:  IMPORTANT: Please copy the full output.
Feb 19 15:37:24:  --------------------------------------------------------
Feb 19 15:37:24:  Checksum      : b0c5c36f45632f6458c53bfee8e4c72f
Feb 19 15:37:24:  Date          : 2021-02-19 15:37:24.685011
Feb 19 15:37:24:  OS            : Linux-5.4.0-39-generic-x86_64-with-debian-stretch-sid
Feb 19 15:37:24:  Game          : csgo
Feb 19 15:37:24:  SP version    : 704
Feb 19 15:37:24:  Github commit : bcea09ef14a15cefdc4a5bd01a1521337af06879
Feb 19 15:37:24:  Server plugins:
Feb 19 15:37:24:     00: Source.Python, (C) 2012-2020, Source.Python Team.
Feb 19 15:37:24:  SP plugins:
Feb 19 15:37:24:     00: es_emulator, https://github.com/Ayuto/EventScripts-Emulator
Feb 19 15:37:24:  --------------------------------------------------------
```

**Comment by NosferatuJoe** [comment]
I've fully reinstalled Source-Python & the emulator. I also tested it with a standard map pool to make sure it's not a map that is causing the crash. As of now the server is clear of crashes and therefor I'll close the issue.

Thanks a lot for all the help and sorry for the hassle, might've been a false positive.
