### ISSUE TITLE
Crash/Freeze

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#6]
https://github.com/Ayuto/EventScripts-Emulator/blob/ea4d3f18f292758188b27e54a2c33c735df1a3ee/addons/source-python/plugins/es_emulator/eventscripts/es_C.py#L2297

This command crashes the server. I guess current just never turns false.

**Comment by Ayuto** [comment]
It's working fine for me. What's the output of ``sp info``?

**Comment by kamikazekuh** [comment]
Updated SP, seems to work fine now, sorry
