### ISSUE TITLE
Shell does not execute command

### ISSUE THREAD

**Issue by kamikazekuh** [Ayuto/EventScripts-Emulator#9]
I've been trying to execute est_effects via the sourcemod plugin "wcs_effects" [https://forums.alliedmods.net/showthread.php?t=139816](url)

This works:

```
import es
def player_say(ev):
	loc = es.getplayerlocation(ev['userid'])
	loc2 = loc
	es.server.queuecmd("es est_effect 3 #a 0 sprites/tp_beam001.vmt %s %s %s %s %s %s 5 5 10 255 0 0 255" % (loc[0],loc[1],loc[2],loc2[0],loc2[1],loc2[2]+100.0))
```

This does not:

```
event player_say
{
	es_getplayerlocation wcs_x1 wcs_y1 wcs_z1 event_var(userid)
	es_getplayerlocation wcs_x2 wcs_y2 wcs_z2 event_var(userid)
	es_math wcs_z2 + 100.0
	es est_effect 3 #a 0 sprites/tp_beam001.vmt server_var(wcs_x1) server_var(wcs_y1) server_var(wcs_z1) server_var(wcs_x2) server_var(wcs_y2) server_var(wcs_z2) 5 5 10 255 0 0 255
}
```

It seems that the shell version does have some issues here.

**Comment by Ayuto** [comment]
Any errors? Could you please also create a snippet that reproduces this issue without the need to install other plugins?

**Comment by kamikazekuh** [comment]
I remade that SM plugin with SP and now it seems to work. issue can be closed!
